### ISSUE TITLE
WebGL.framework.js: buffer is not defined

### ISSUE THREAD

**Issue by jygeer** [inworld-ai/inworld-unity#26]
WebGL target with Inworld microphone enabled browser fails.

WebGL.framework.js:9 Uncaught (in promise) ReferenceError: buffer is not defined
    at _WebGLInitSamplesMemoryData (WebGL.framework.js:9:138896)
    at WebGL.wasm:0x13f2cb3
    at WebGL.wasm:0x13f3cef
    at WebGL.wasm:0x1672b11
    at WebGL.wasm:0x1d262b8
    at WebGL.wasm:0x1d3c5d7
    at WebGL.wasm:0x27ab0e3
    at invoke_iiii (WebGL.framework.js:9:435124)
    at WebGL.wasm:0x1d3b5c0
    at WebGL.wasm:0x11fff9
    at WebGL.wasm:0x26df00e
    at WebGL.wasm:0x269add0
    at WebGL.wasm:0x269319b
    at WebGL.wasm:0x269b172
    at WebGL.wasm:0x269319b
    at WebGL.wasm:0x270c2a2
    at WebGL.wasm:0x1677463
    at WebGL.wasm:0x13f26d7
    at WebGL.wasm:0x27ab104
    at invoke_vii (WebGL.framework.js:9:434649)
    at WebGL.wasm:0x13f22ea
    at WebGL.wasm:0x27ab104
    at invoke_vii (WebGL.framework.js:9:434649)
    at WebGL.wasm:0x13f1f6f
    at WebGL.wasm:0x27ab128
    at Object.unityCommand (WebGL.framework.js:9:138517)
    at InworldMicrophone.setPermissionStatus (InworldMicrophone.js:215:35)
    at InworldMicrophone.permissionStatusHandler (InworldMicrophone.js:209:22)

**Comment by Juniverse** [comment]
Hello @jygeer ,

Sorry for the inconvenience, may I know which browser are you using?

**Comment by jygeer** [comment]
Chrome (Windows, MacOS and iOS) all throw an error.

Reference https://github.com/inworld-ai/inworld-unity-core/blob/main/Runtime/UnityWebSocket/Plugins/WebGL/InworldMicrophoneInterop.jslib

``
  WebGLInitSamplesMemoryData: function(byteOffset, length) 
    {
        document.microphoneNative.samplesMemoryData = new Float32Array(buffer, byteOffset, length);
    },

``
